import express from 'express';
// import jwt from 'jwt-simple'; // Note: using jsonwebtoken below
import pkg from 'jsonwebtoken';
const { sign, verify } = pkg;
import { supabase } from '../lib/supabase.js';
import { requireAuth } from '../middleware/authMiddleware.js';

const router = express.Router();

// Secret keys from environment variables
const JWT_SECRET = process.env.JWT_SECRET || 'super-long-random';

// POST /api/auth/register
router.post('/register', async (req, res) => {
  try {
    const { email, password, display_name } = req.body;

    // Use Supabase Auth to create the user
    // The database trigger will automatically create the public.profiles row
    const { data, error } = await supabase.auth.signUp({
      email: email,
      password: password,
      options: {
        data: {
          name: display_name // This gets passed to raw_user_meta_data to populate the profile
        }
      }
    });

    if (error) throw error;

    res.status(201).json({ message: 'User registered successfully', data });
  } catch (error) {
    res.status(400).json({ error: { code: 'BAD_REQUEST', message: error.message } });
  }
});

// POST /api/auth/login
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({
        error: { code: 'BAD_REQUEST', message: 'Email and password are required' }
      });
    }

    // 1. Authenticate with Supabase Auth
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password
    });

    if (error || !data.session) {
      return res.status(401).json({
        error: { code: 'UNAUTHORIZED', message: error?.message || 'Invalid credentials' }
      });
    }

    const { session, user } = data;

    // 2. Set the short-lived access token in an httpOnly cookie
    res.cookie('accessToken', session.access_token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'none',
      maxAge: 15 * 60 * 1000 // 15 minutes
    });

    res.json({ message: 'Logged in successfully', user: { id: user.id, email: user.email, name: user.user_metadata?.display_name || '' } });
  } catch (error) {
    res.status(500).json({ error: { code: 'INTERNAL_SERVER_ERROR', message: error.message } });
  }
});

// POST /api/auth/logout
router.post('/logout', (req, res) => {
  res.clearCookie('accessToken');
  res.json({ message: 'Logged out successfully' });
});

// GET /api/auth/google
// Redirects the user to the Google consent screen
router.get('/google', async (req, res) => {
  try {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        redirectTo: 'http://localhost:3000/api/auth/callback'
      }
    });

    if (error) throw error;
    
    // Redirect the client to the Google OAuth URL generated by Supabase
    res.redirect(data.url);
  } catch (error) {
    res.status(500).json({ error: { code: 'INTERNAL_SERVER_ERROR', message: error.message } });
  }
});

// GET /api/auth/callback
// Handles the redirect from Supabase after successful Google login
router.get('/callback', async (req, res) => {
  // Supabase automatically handles the code exchange via the client SDK.
  // In a pure backend setup, you would capture the session token here 
  // and set it as an httpOnly cookie, similar to standard login.
  
  // Note: For SPAs (Next.js/React), this code exchange is often better 
  // handled directly on the frontend using the Supabase JS client.
  res.redirect(`${process.env.CORS_ORIGIN}/dashboard?login=success`);
});

// GET /api/auth/me
// Returns the current session user data
router.get('/me', requireAuth, async (req, res) => {
  try {
    // req.user.userId comes from the verified JWT payload
    const { data: user, error } = await supabase
      .from('profiles')
      .select('id, email, display_name, avatar_url')
      .eq('id', req.user.userId)
      .single();

    if (error || !user) {
      return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'User not found' } });
    }

    res.json({ user });
  } catch (error) {
    res.status(500).json({ error: { code: 'INTERNAL_SERVER_ERROR', message: error.message } });
  }
});

export default router;